services:
  devops:
    build: .
    image: devops:latest
    container_name: devops1
    restart: always
    ports:
      - "8080:8080"
    networks:
      - devopsNet

networks:
  devopsNet:
    external: true