version: '3.8'

include:
  - docker-compose-db.yml

services:
  devops:
    build: .
    image: devops:latest
    container_name: devops1
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-server:5432/${POSTGRES_DB:-iwvg_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    depends_on:
      - postgres
    networks:
      - devopsNet