server:
  port: ${PORT:8080}

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: none
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-server:5432/devops_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

info:
  app:
    artifact: "@project.artifactId@"
    version: "@project.version@"
    build: "@maven.build.timestamp@"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true