app:
  hosting: render

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: WARN
    es.upm.miw: DEBUG

server:
  port: ${PORT:8080}